Http/routes.php
<?php


Route::group(['middleware' => ['web']], function () {
    Route::group(["prefix" => "admin", "as" => "admin."], function () {
        Route::group(['middleware' => 'auth:dcms'], function () {

            //POSPRODUCTS
            Route::group(["prefix" => "posproducts", "as" => "posproducts."], function () {

                //CATEGORIES
                Route::group(["prefix" => "categories", "as" => "categories."], function () {
                    Route::get("{id}/copy", ["as" => "{id}.copy", "uses" => "POSCategoryController@copy"]);
                    Route::any("api/table", ["as" => "api.table", "uses" => "POSCategoryController@getDatatable"]);
                    Route::any("rebuildTree", ["as" => "rebuildTree", "uses" => "POSCategoryController@rebuildTree"]);
                });
                Route::resource("categories", "POSCategoryController");

                //INFORMATION
                Route::group(["prefix" => "information", "as" => "information."], function () {
                    Route::any("api/table", ["as" => "api.table", "uses" => "POSInformationController@getDatatable"]);
                    Route::any("api/articlerelationtable/{article_id?}", ["as" => "api.articlerelationtable", "uses" => "POSInformationController@getArticleRelationTable"]);
                    Route::any("api/plantrelationtable/{plant_id?}", ["as" => "api.plantrelationtable", "uses" => "POSInformationController@getPlantRelationTable"]);
                });

                //API
                Route::group(array("prefix" => "api","as"=>"api."), function () {
                    Route::any("table", ["as" => "table", "uses" => "POSProductController@getDatatable"]);
                });

                Route::resource("information", "POSInformationController");
            });

            Route::resource("posproducts", "POSProductController");
        });
    });
});

Models/POSProduct.php
<?php

namespace Dcms\PosProducts\Models;

use Dcms\Core\Models\EloquentDefaults;

use Auth;

class POSProduct extends EloquentDefaults
{
    protected $connection = 'project';
    protected $table  = "posproducts";

    public function information()
    {
        return $this->belongsToMany('\Dcms\PosProducts\Models\POSInformation', 'posproducts_to_products_information', 'posproduct_id', 'posproduct_information_id')->withTimestamps();
    }
}

Http/Controllers/POSProductController.php
<?php

namespace Dcms\PosProducts\Http\Controllers;

use App\Http\Controllers\Controller;

use Dcms\PosProducts\Models\POSCategory;
use Dcms\PosProducts\Models\POSInformation;
use Dcms\PosProducts\Models\POSProduct;
use Dcms\Products\Models\Product;
use Dcms\Products\Models\Information;
use Dcms\Products\Models\Attachment;
use Dcms\Products\Models\Price;

use Illuminate\Support\Str;
use View;
use Input;
use Session;
use Validator;
use Redirect;
use DB;
use DataTables;
use Auth;

class POSProductController extends Controller
{
    public $informatationColumNames = [];
    public $informatationColumNamesDefaults = []; // TO DO - the input on the information tab are array based
    public $productColumNames = [];
    public $productColumnNamesDefaults = []; // e.g. checkboxes left blank will result in NULL database value, if this is not what you want, you can set e.g. array('checkbox_name'=>'0');
    public $extendgeneralTemplate = "";
    public $informationTemplate = "";
    public $information_group_id = "";

    public function __construct()
    {
        $this->middleware('permission:posproducts-browse')->only('index');
        $this->middleware('permission:posproducts-add')->only(['create', 'store']);
        $this->middleware('permission:posproducts-edit')->only(['edit', 'update']);
        $this->middleware('permission:posproducts-delete')->only('destroy');

        $this->informationColumNames = [
            'title'                    => 'information_name'
            , 'description'            => 'information_description'
            , 'description_short'      => 'information_description_short'
            , 'sort_id'                => 'information_sort_id'
            , 'posproduct_category_id' => 'posinformation_category_id'
            , 'url_slug'               => 'information_name',
        ];

        $this->productColumNames = [
            'code'             => 'code'
            , 'image'          => 'image'
            , 'volume'         => 'volume'
            , 'volume_unit_id' => 'volume_unit_id',
        ];

        $this->extendgeneralTemplate = null;
        $this->informationTemplate = null;
        $this->information_group_id = null;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return View::make('dcmsposproducts::posproducts/index');
    }

    /**
     * get the data for DataTable JS plugin.
     *
     * @return Response
     */
    public function getDatatable()
    {
        return DataTables::queryBuilder(
            DB::connection("project")->table("posproducts")->select(
                "posproducts.id",
                "posproducts.code",
                "posproducts_to_products_information.posproduct_information_id as info_id",
                "title",
                DB::raw('CONCAT(volume, " ", volume_unit) AS volume'),
                (DB::connection("project")->raw("concat(\"<img src='/packages/Dcms/Core/images/flag-\", lcase(countries.country),\".png' > \") as country"))
            )
                ->leftJoin('posproducts_to_products_information', 'posproducts.id', '=', 'posproducts_to_products_information.posproduct_id')
                ->leftJoin('posproducts_information', 'posproducts_information.id', '=', 'posproducts_to_products_information.posproduct_information_id')
                ->leftJoin('posproducts_volume_units', 'posproducts.volume_unit_id', '=', 'posproducts_volume_units.id')
                ->leftJoin('languages', 'posproducts_information.language_id', '=', 'languages.id')
                ->leftJoin('countries', 'languages.country_id', '=', 'countries.id')
        )
            ->addColumn('edit', function ($model) {
                $edit = '<form method="POST" action="/admin/posproducts/' . (isset($model->info_id) ? $model->info_id : $model->id) . '" accept-charset="UTF-8" class="pull-right"> <input name="_token" type="hidden" value="' . csrf_token() . '"> <input name="_method" type="hidden" value="DELETE">
                						<input type="hidden" name="table" value="' . (isset($model->info_id) ? "information" : "product") . '"/>
                						<input type="hidden" name="posproduct_id" value="' . $model->id . '"/>';

                if (Auth::user()->can('products-edit')) {
                    $edit .= '<a class="btn btn-xs btn-default" href="/admin/posproducts/' . $model->id . '/edit"><i class="far fa-pencil"></i></a>';
                }
                if (Auth::user()->can('products-delete')) {
                    $edit .= '<button class="btn btn-xs btn-default" type="submit" value="Delete this POS product" onclick="if(!confirm(\'Are you sure to delete this item ? \')){return false;};"><i class="far fa-trash-alt"></i></button>';
                }
                $edit .= '</form>';

                return $edit;
            })
            ->rawColumns(['country', 'edit'])
            ->make(true);
    }

    //return the model/object (id, country, language) or an array e.g. array(language_id => language-COUNTRY)
    public function getCountriesLanguages($returnType = "array")
    {
        //RFC 3066
        $oCountriesLanguages = DB::connection("project")->select('SELECT id, country, language FROM languages ');

        if ($returnType === "model") {
            return $oCountriesLanguages;
        } else {
            $aCountryLanguage = [];

            if (!is_null($oCountriesLanguages) && count($oCountriesLanguages) > 0) {
                foreach ($oCountriesLanguages as $M) {
                    $aCountryLanguage[$M->id] = strtolower($M->language) . "-" . strtoupper($M->country);
                }
            }

            return $aCountryLanguage;
        }
    }

    //return the model/object or an array e.g. array(counrty_id => counryname)
    public function getCountries($returnType = "array")
    {
        $oCountries = DB::connection("project")->select('SELECT id, country_name FROM countries');
        if ($returnType === "model") {
            return $oCountries;
        } else {
            $aCountries = [];

            foreach ($oCountries as $c) {
                $aCountries[$c->id] = $c->country_name;
            }

            return $aCountries;
        }
    }

    public function getVolumesClasses($returnType = "array")
    {
        //volumeclasses
        //there is no model for VOLUMES so no eloquent querying here
        $oVolumeClasses = DB::connection("project")->select('SELECT id, volume_unit as volume FROM posproducts_volume_units ORDER BY 2');

        if ($returnType === "model") {
            return $oVolumeClasses;
        } else {
            //there was no support for the lists() method
            $aVolumesClasses = [];

            foreach ($oVolumeClasses as $v) {
                $aVolumesClasses[$v->id] = $v->volume;
            }

            return $aVolumesClasses;
        }
    }

    //return the model to fill the form
    public function getExtendedModel()
    {
        //do nothing sit back and make the extension hook up.
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $languageinformation = $this->getInformation();

        return View::make('dcmsposproducts::posproducts/form')
            ->with('languageinformation', $languageinformation)
            ->with('informationtemplate', $this->informationTemplate)//giving null will make a fallback to the default productinformation template on the package
            ->with('volumeclasses', $this->getVolumesClasses("array"))
            ->with('categoryOptionValues', POSCategory::OptionValueTreeArray(false))
            ->with('sortOptionValues', $this->getSortOptions($languageinformation, 1));
    }

    protected function validateProductForm()
    {
        // validate
        // read more on validation at http://laravel.com/docs/validation
        $rules = [
            'code' => 'required',
        ];
        $validator = Validator::make(request()->all(), $rules);

        // process the login
        if ($validator->fails()) {
            return Redirect::back()//to('admin/products/' . $id . '/edit')
            ->withErrors($validator)
                ->withInput();
        } else {
            return true;
        }
    }


    /**
     * Store the product based on a productid or a new product
     *
     * @return Product Object
     */
    protected function saveProductProperties($productid = null)
    {
        // do check if the given id is existing.
        if (!is_null($productid) && intval($productid) > 0) {
            $Product = POSProduct::find($productid);
        }

        if (!isset($Product) || is_null($Product)) {
            $Product = new POSProduct;
        }

        foreach ($this->productColumNames as $column => $inputname) {
            if (!request()->has($inputname) && array_key_exists($inputname, $this->productColumnNamesDefaults)) {
                $Product->$column = $this->productColumnNamesDefaults[$inputname];
            } else {
                $Product->$column = request()->get($inputname);
            }
        }

        $Product->save();
        $Product->information()->detach(); //detach any information setting, this will be set up using teh saveProductInformation() method

        return $Product;
    }

    /**
     * Save the ProductInformation to the given product (object)
     * this can be filtered by givin a single languageid - the filter helps for returning the model of the saved Information
     * by default you get back the last saved Information object
     * @return Product Object
     */
    protected function saveProductInformation(POSProduct $Product, $givenlanguage_id = null)
    {
        $input = request()->all();

        $pInformation = null; //pInformation = object product Information

        if (isset($input["information_language_id"]) && count($input["information_language_id"]) > 0) {

resources/views/posproducts/form.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
        <h1>POS Products</h1>
        <ol class="breadcrumb">
            <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
            <li><a href="{!! URL::to('admin/posproducts') !!}"><i class="far fa-shopping-cart"></i> POS Products</a></li>
            @if(isset($posproduct))
                <li class="active"><i class="far fa-pencil"></i>POS Product {{$posproduct->id}}</li>
            @else
                <li class="active"><i class="far fa-plus-circle"></i> Create POS Product</li>
            @endif
        </ol>
        @if(isset($posproduct))
            <p class="edit">Last edited by {{ $posproduct->admin }} on {{ Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $posproduct->updated_at)->format('d-m-Y H:i:s') }}</p>
        @endif
    </div>

    <div class="main-content">
        <div class="row">

            @if(isset($posproduct))
                {!! Form::model($posproduct, array('route' => array('admin.posproducts.update', $posproduct->id), 'method' => 'PUT')) !!}
            @else
                {!! Form::open(array('url' => 'admin/posproducts')) !!}
            @endif

            <div class="col-md-12">

                <div class="main-content-tab tab-container">
                    @if (!is_array($categoryOptionValues) || count($categoryOptionValues)<=0 )    Please first create a <a
                            href="{!! URL::to('admin/posproducts/categories/create') !!}"> POS product category </a>  @else
                        <ul class="nav nav-tabs" role="tablist">
                            <li class="active"><a href="#data" role="tab" data-toggle="tab">Data</a></li>
                            <li><a href="#information" role="tab" data-toggle="tab">Information</a></li>
                        </ul>

                        <div class="tab-content">
                            @if($errors->any())
                                <div class="alert alert-danger">{!! Html::ul($errors->all()) !!}</div>
                            @endif
                            <div id="data" class="tab-pane active">
                                <!-- #data -->

                                <!-- #Code -->
                                <div class="form-group">
                                    {!! Form::label('code', 'Code') !!}
                                    {!! Form::text('code', old('code'), array('class' => 'form-control')) !!}
                                </div>

                                <div class="form-group">
                                    {!! Form::label('image', 'Image') !!}
                                    <div class="input-group">
                                        {!! Form::text('image', old('image'), array('class' => 'form-control')) !!}
                                        <span class="input-group-btn">{!! Form::button('Browse Server', array('class' => 'btn btn-primary browse-server' , 'id'=>'browse_image')) !!}</span>
                                    </div>
                                </div>

                                <!-- #Volume + unitclass (kg - l - g - ...) -->
                                <div class="row">
                                    <div class="col-sm-10">
                                        <div class="form-group">
                                            {!! Form::label('volume', 'Volume') !!}
                                            {!! Form::text('volume', old('volume'), array('class' => 'form-control')) !!}
                                        </div>
                                    </div>
                                    <div class="col-sm-2">
                                        <div class="form-group">
                                            {!! Form::label('volume_unit_id', 'Unit') !!}
                                            {!! Form::select('volume_unit_id', (array(null=>'') + $volumeclasses), old('volume_unit_id'), array('class' => 'form-control')); !!}
                                        </div>
                                    </div>
                                </div>

                            <!-- #data -->
                            </div>

                            <div id="information" class="tab-pane">
                                <!-- #information -->
                                <div class="tab-container">

                                    @if(isset($languageinformation))

                                        <ul class="nav nav-tabs" role="tablist">
                                            @foreach($languageinformation as $key => $language)
                                                <li class="{!! ((intval(session('overrule_default_by_language_id')) == 0 && $key == 0) ? 'active' : '') !!}"><a href="{!! '#' . $language->language . '-' . $language->country !!}"
                                                                                                   role="tab" data-toggle="tab"><img
                                                                src="{!! asset('/packages/Dcms/Core/images/flag-' . strtolower($language->country) . '.png') !!}" width="16"
                                                                height="16"/> {!! $language->language_name !!}</a></li>
                                            @endforeach
                                        </ul>

                                        <div class="tab-content">
                                            @if(!isset($informationtemplate) || is_null($informationtemplate) )
                                                @include('dcmsposproducts::posproducts/templates/information', array('languageinformation'=>$languageinformation,'sortOptionValues'=>$sortOptionValues))
                                                @yield('information')
                                            @else
                                                @include($informationtemplate, array('languageinformation'=>$languageinformation,'sortOptionValues'=>$sortOptionValues))
                                                @yield('information')
                                            @endif
                                        </div>

                                    @endif

                                </div>
                                <!-- #information -->
                            </div>

                        </div><!-- end tab-content -->
                    @endif
                </div><!-- end main-content-tab -->
            </div><!-- end col-md-12 -->

            <div class="col-md-12">
                <div class="main-content-block">
                    {!! Form::submit('Save', array('class' => 'btn btn-primary')) !!}
                    <a href="{!! URL::previous() !!}" class="btn btn-default">Cancel</a>
                </div>
            </div>

            {!! Form::close() !!}

        </div><!-- end row -->
    </div><!-- end main-content -->

@stop

@section("script")

    <script type="text/javascript" src="{!! asset('/packages/Dcms/Core/js/bootstrap.min.js') !!}"></script>
    <script type="text/javascript" src="{!! asset('/packages/Dcms/Core/ckeditor/ckeditor.js') !!}"></script>
    <script type="text/javascript" src="{!! asset('/packages/Dcms/Core/ckeditor/adapters/jquery.js') !!}"></script>
    <script type="text/javascript" src="{!! asset('/packages/Dcms/Core/ckfinder/ckfinder.js') !!}"></script>
    <script type="text/javascript" src="{!! asset('/packages/Dcms/Core/ckfinder/ckbrowser.js') !!}"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            //CKFinder for CKEditor
            CKFinder.setupCKEditor(null, '/packages/Dcms/Core/ckfinder/');

            //CKEditor
            $("textarea.ckeditor").ckeditor();

            //CKFinder
            $(".browse-server").click(function () {
                var returnid = $(this).attr("id").replace("browse_", "");
                BrowseServer('image:/', returnid);
            });

            //Bootstrap Tabs
            $(".tab-container .nav-tabs a").click(function (e) {
                e.preventDefault();
                $(this).tab('show');
            });

            //ColorPicker
            $(".period-box .checkbox-group input").each(function () {
                $inputName = $(this).attr('name');
                $('[name="' + $inputName + '"]').paletteColorPicker({
                    clear_btn: null,
                    timeout: 700
                });
            });


            $('#information .input-group .information-id-reset').click(function () {
                $(this).closest(".tab-pane").find("input[id^='information_id']").val("");
                return false;
            });

            $("body").on("click", ".browse-server-files", function () {
                var returnid = $(this).attr("id").replace("browse_", "");
                BrowseServer('Files:/', returnid);
            });
        });
    </script>

@stop

resources/views/posproducts/index.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
        <h1>POS Products</h1>
        <ol class="breadcrumb">
            <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
            <li class="active"><i class="far fa-shopping-cart"></i> POS Products</li>
        </ol>
    </div>

    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="main-content-block">

                    @if (Session::has('message'))
                        <div class="alert alert-info">{!! Session::get('message') !!}</div>
                    @endif

                    @can('products-add')
                        <div class="btnbar btnbar-right"><a class="btn btn-small btn-primary" href="{!! URL::to('admin/posproducts/create') !!}">Create new</a></div>
                    @endcan

                    <h2>Overview</h2>


                    <table id="datatable" class="table table-hover table-condensed" style="width:100%">
                        <thead>
                        <tr>
                            <th>Code</th>
                            <th>Title</th>
                            <th>Volume</th>
                            <th>Country</th>
                            <th>ID</th>
                            <th></th>
                        </tr>
                        </thead>
                    </table>

                    <script type="text/javascript">
                        $(document).ready(function () {
                            oTable = $('#datatable').DataTable({
                                "pageLength": 50,
                                "processing": true,
                                "serverSide": true,
                                "ajax": "{{ route('admin.posproducts.api.table') }}",
                                "columns": [
                                    {data: 'code', name: 'posproducts.code'},
                                    {data: 'title', name: 'posproducts_information.title'},
                                    {data: 'volume', name: 'volume', searchable: false},
                                    {data: 'country', name: 'country', searchable: false},
                                    {data: 'id', name: 'id'},
                                    {data: 'edit', name: 'edit', orderable: false, searchable: false}
                                ]
                            });
                        });
                    </script>

                    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.css">

                    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
                    <script type="text/javascript" language="javascript"
                            src="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.js"></script>

                    <script type="text/javascript">
                        $(document).ready(function () {

                            $(document).on("click", ".delete", function (e) {
                                bootbox.confirm("Are you sure?", function (result) {
                                    Example.show("Confirm result: " + result);
                                });
                            });

                        });
                    </script>

                    <script type="text/javascript" src="{!! asset('/packages/Dcms/Core/js/bootstrap.min.js') !!}"></script>
                    <script type="text/javascript" src="{!! asset('/packages/Dcms/Core/js/bootbox.min.js') !!}"></script>

                </div>
            </div>
        </div>
    </div>

@stop